### ISSUE TITLE
Format some characters which are full-width

### ISSUE THREAD

**Issue by reply2future** [FelisDiligens/md-table-tools#2] opened 2024-03-30 03:44 UTC
## problem
When I input some content like Traditional Chinese and pretty render the markdown table would be not pretty because of the these full-width characters.
I wrote a test like that:
<img width="312" alt="image" src="https://github.com/FelisDiligens/md-table-tools/assets/6359152/510d541e-262a-47c4-b003-29ca04604577">

BTW, I used your plugin of joplin, thanks for your great work and I'm looking forward to this feature :)

**Comment by FelisDiligens** [comment] 2024-05-10 08:03
PR merged, thanks! :)

**Closed by FelisDiligens** 2024-05-10 08:03 UTC

**Comment by Stainless5792** [comment] 2024-05-15 05:46
> PR merged, thanks! :)

Hi @FelisDiligens, I tried this in the web demo page, and saw the issue is still there.
<img width="1362" alt="image" src="https://github.com/FelisDiligens/md-table-tools/assets/5257915/d7fd6ad0-5824-47c6-927e-3c15f874fe37">

And after updated to the new version in my Joplin, seems also doesn't work, anything else I missed ?
<img width="548" alt="image" src="https://github.com/FelisDiligens/md-table-tools/assets/5257915/31d5758f-3bcb-4b7d-912e-6b0cbfd8b2c5">
<img width="279" alt="image" src="https://github.com/FelisDiligens/md-table-tools/assets/5257915/7ca54a46-d3f9-4ef4-b560-f254690fb918">

**Comment by FelisDiligens** [comment] 2024-05-15 14:39
Hi @Stainless5792,

> I tried this in the web demo page, and saw the issue is still there.

Sorry, I haven't updated the demo page yet.

> And after updated to the new version in my Joplin, seems also doesn't work, anything else I missed ?

I noticed that too... depending on the used font family, full-width characters are between 1 and 2 "regular" characters long. The code just assumes, that a full-width character is exactly 2 regular characters or 2 spaces long. It works great in a terminal (see the green line in the reply2future's picture), but not well in Joplin.

As a workaround, you may want to test a few font families...
Here's "Hack":
![Hack](https://github.com/FelisDiligens/md-table-tools/assets/47528453/f5310f9c-424c-448c-8cc7-77e77bb77e25)

And here's "Ubuntu Mono":
![Ubuntu Mono](https://github.com/FelisDiligens/md-table-tools/assets/47528453/bf9fa581-280f-4141-a86a-735dcaf1d238)
Here it aligns properly but with Hack it doesn't... not sure why.

**Comment by reply2future** [comment] 2024-05-17 04:32
Although Hack is [monospace font](https://en.wikipedia.org/wiki/Monospaced_font), but it doesn't work well with Chinese characters. [ref](https://github.com/source-foundry/Hack/issues/341#issuecomment-1023293301)

It looks like the problem about joplin HTML display. I have not idea about that.

**Comment by Stainless5792** [comment] 2024-05-24 05:13
@FelisDiligens @reply2future So appreciated for your replies ! I will give it a try!
